### PR TITLE
Fix build in PHP 5.4

### PR DESCRIPTION
**Pull request by gslin**

### CODE REVIEW

**Comment by Tatsh** [comment]
+1

**Comment by owend** [comment]
Hi. Can you post a new version which incorporates this fix to PECL?  Right now the recommended installation instructions fail on PHP 5.4:

/tmp/pear/temp/test_helpers/test_helpers.c: In function ‘pth_get_zval_ptr’:
/tmp/pear/temp/test_helpers/test_helpers.c:105: error: ‘union <anonymous>’ has no member named ‘var’

Download from github and compiling manually works though.  Thanks!

**Comment by willemstuursma** [comment]
+1

**Comment by RickWong** [comment]
+1
