### ISSUE TITLE
php 5.4.0

### ISSUE THREAD

**Issue by tonypizzicato** [php-test-helpers/php-test-helpers#15]
Can not compile with php 5.4.0(Zend Engine API version 220100525)

/home/agrebnev/src/php-test-helpers/test_helpers.c: In function 'pth_get_zval_ptr':
/home/agrebnev/src/php-test-helpers/test_helpers.c:156:10: error: 'union <anonymous>' has no member named 'var'
/home/agrebnev/src/php-test-helpers/test_helpers.c:158:23: error: 'union <anonymous>' has no member named 'var'
/home/agrebnev/src/php-test-helpers/test_helpers.c:161:43: error: 'union <anonymous>' has no member named 'var'
/home/agrebnev/src/php-test-helpers/test_helpers.c:163:68: error: 'union <anonymous>' has no member named 'var'
/home/agrebnev/src/php-test-helpers/test_helpers.c: In function 'pth_new_handler':
/home/agrebnev/src/php-test-helpers/test_helpers.c:207:11: error: 'znode_op' has no member named 'u'
/home/agrebnev/src/php-test-helpers/test_helpers.c:231:2: error: 'znode_op' has no member named 'u'
/home/agrebnev/src/php-test-helpers/test_helpers.c: In function 'pth_exit_handler':
/home/agrebnev/src/php-test-helpers/test_helpers.c:254:2: warning: passing argument 1 of 'pth_get_zval_ptr' from incompatible pointer type [enabled by default]
/home/agrebnev/src/php-test-helpers/test_helpers.c:148:14: note: expected 'struct znode _' but argument is of type 'union znode_op *'
make: *_\* [test_helpers.lo] Error 1

**Comment by sebastianbergmann** [comment]
Fixed in `master`.
