### ISSUE TITLE
Does not compile with PHP 5.3.99

### ISSUE THREAD

**Issue by sebastianbergmann** [php-test-helpers/php-test-helpers#9]
```
/usr/local/src/test-helpers/test_helpers.c: In function ‘pth_get_zval_ptr’:
/usr/local/src/test-helpers/test_helpers.c:108:10: error: ‘union <anonymous>’ has no member named ‘var’
/usr/local/src/test-helpers/test_helpers.c:110:23: error: ‘union <anonymous>’ has no member named ‘var’
/usr/local/src/test-helpers/test_helpers.c:113:43: error: ‘union <anonymous>’ has no member named ‘var’
/usr/local/src/test-helpers/test_helpers.c:115:68: error: ‘union <anonymous>’ has no member named ‘var’
/usr/local/src/test-helpers/test_helpers.c: In function ‘pth_new_handler’:
/usr/local/src/test-helpers/test_helpers.c:159:11: error: ‘znode_op’ has no member named ‘u’
/usr/local/src/test-helpers/test_helpers.c:183:2: error: ‘znode_op’ has no member named ‘u’
/usr/local/src/test-helpers/test_helpers.c: In function ‘pth_exit_handler’:
/usr/local/src/test-helpers/test_helpers.c:206:2: warning: passing argument 1 of ‘pth_get_zval_ptr’ from incompatible pointer type
/usr/local/src/test-helpers/test_helpers.c:100:14: note: expected ‘struct znode *’ but argument is of type ‘union znode_op *’
```

**Comment by johannes** [comment]
PHP trunk is a pre-alpha development version. A moving target. This is not supported by me.

**Comment by sebastianbergmann** [comment]
Okay, nevermind.
